package postgres

import (
	"context"
	"fmt"
	"time"

	"dealdet/internal/domain"
)

// Alert persistence layer.
// 1 InsertAlert is idempotent by idempotency key, which is generated by hashing the watch target ID
//  and deal candidate ID together.
//
// MarkAlertSent and MarkAlertFailed update the status of an alert by idempotency key.

func (s *Store) InsertAlert(ctx context.Context, row domain.AlertRow) (bool, error) {
	pool, err := s.poolOrError()
	if err != nil {
		return false, err
	}

	result, err := pool.Exec(ctx, `
		INSERT INTO alert (
			watch_target_id,
			deal_candidate_id,
			tier,
			channel,
			idempotency_key,
			user_email,
			user_phone
		) VALUES ($1, $2, $3, $4, $5, $6, $7)
		ON CONFLICT (idempotency_key) DO NOTHING
	`,
		row.WatchTargetID,
		row.DealCandidateID,
		row.Tier,
		row.Channel,
		row.IdempotencyKey,
		row.UserEmail,
		row.UserPhone,
	)
	if err != nil {
		return false, fmt.Errorf("insert alert %s: %w", row.IdempotencyKey, err)
	}

	return result.RowsAffected() == 1, nil
}

func (s *Store) MarkAlertSent(ctx context.Context, idempotencyKey string, sentAt time.Time) error {
	pool, err := s.poolOrError()
	if err != nil {
		return err
	}

	result, err := pool.Exec(ctx, `
		UPDATE alert
		SET status = 'sent', sent_at = $2, updated_at = NOW(), error_message = ''
		WHERE idempotency_key = $1
	`, idempotencyKey, sentAt)
	if err != nil {
		return fmt.Errorf("mark alert sent %s: %w", idempotencyKey, err)
	}
	if result.RowsAffected() == 0 {
		return fmt.Errorf("alert not found for idempotency key %s", idempotencyKey)
	}

	return nil
}

func (s *Store) MarkAlertFailed(ctx context.Context, idempotencyKey string, message string) error {
	pool, err := s.poolOrError()
	if err != nil {
		return err
	}

	result, err := pool.Exec(ctx, `
		UPDATE alert
		SET status = 'failed', error_message = $2, updated_at = NOW()
		WHERE idempotency_key = $1
	`, idempotencyKey, message)
	if err != nil {
		return fmt.Errorf("mark alert failed %s: %w", idempotencyKey, err)
	}
	if result.RowsAffected() == 0 {
		return fmt.Errorf("alert not found for idempotency key %s", idempotencyKey)
	}

	return nil
}
